# Generated by Django 3.2.6 on 2021-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20210825_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.TextField(max_length=30),
        ),
    ]
