# Generated by Django 3.2.6 on 2021-08-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20210825_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
