# Generated by Django 3.2.6 on 2021-08-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
