# Generated by Django 3.2.6 on 2021-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0013_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('model', models.TextField(max_length=30)),
                ('year', models.TextField(max_length=30)),
                ('vin', models.TextField(max_length=30)),
                ('price_currency', models.TextField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
