# Generated by Django 3.2.6 on 2021-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
