# Generated by Django 3.2.6 on 2021-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_car_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
