# Generated by Django 3.2.6 on 2021-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
