# Generated by Django 3.2.6 on 2021-08-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_alter_newsletter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('phone_cell', models.IntegerField(unique=True)),
                ('chosen_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.car')),
            ],
        ),
    ]
