# Generated by Django 3.2.6 on 2021-08-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('price',)},
        ),
    ]
