# Generated by Django 3.2.6 on 2021-08-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_alter_car_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='chosen_car',
        ),
        migrations.AddField(
            model_name='client',
            name='model_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_car', to='main_page.car'),
        ),
    ]
