# Generated by Django 3.2.6 on 2021-08-31 16:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20210831_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_cell',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
